version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-connect-vanity-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2ggs48k5u7je"
s3_prefix = "aws-connect-vanity-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
