# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS Connect SAM - Vanity Number Generator App

Globals:
  Function:
    Runtime: nodejs14.x
# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  VanityPhoneNumberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: callerPhoneNumber
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: callerPhoneNumber
          AttributeType: S

  VanityPhoneNumberConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers
      Handler: vanity-phone-number-converter.handler
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref VanityPhoneNumberTable
      Description: A Lambda function that accepts a caller's phone number and stores the 5 best resulting vanity numbers in a DynamoDB table.
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref VanityPhoneNumberTable

Outputs:
  VanityPhoneNumberTable:
    Description: Name of the DynamoDB Vanity Phone Numbers Table
    Value: !Ref VanityPhoneNumberTable
    Export:
      Name: !Sub "${AWS::StackName}-VanityPhoneNumberTableName"
  VanityPhoneNumberConverterFunction:
    Description: Vanity Phone Number Converter Function ARN
    Value: !GetAtt VanityPhoneNumberTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-VanityPhoneNumberConverterFunction"
