AWSTemplateFormatVersion: 2010-09-09
Description: AWS Connect SAM - Vanity Number Generator App
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 8
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  VanityPhoneNumberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: callerPhoneNumber
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: callerPhoneNumber
          AttributeType: S

  VanityPhoneNumberConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: webpack-bundle.handler
      MemorySize: 4096
      Environment:
        Variables:
          TABLE_NAME: !Ref VanityPhoneNumberTable
      Description: A Lambda function that accepts a caller's phone number and stores the 5 best resulting vanity numbers in a DynamoDB table.
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref VanityPhoneNumberTable

Outputs:
  VanityPhoneNumberTable:
    Description: Name of the DynamoDB Vanity Phone Numbers Table
    Value: !Ref VanityPhoneNumberTable
    Export:
      Name: !Sub "${AWS::StackName}-VanityPhoneNumberTableName"
  VanityPhoneNumberConverterFunction:
    Description: Vanity Phone Number Converter Function ARN
    Value: !GetAtt VanityPhoneNumberConverterFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-VanityPhoneNumberConverterFunction"
